import { ChainConfig } from "./types";

export const EVM_CHAINS: ChainConfig[] = [
  // TESTNETS
  {
    id: "eth-sepolia",
    chainId: 11155111,
    hexChainId: "0xaa36a7",
    name: "Ethereum Sepolia",
    shortName: "Sepolia",
    network: "testnet",
    rpcUrls: [
      "https://rpc.sepolia.org",
      "https://eth-sepolia.g.alchemy.com/v2/demo",
      "https://sepolia.infura.io/v3/",
    ],
    blockExplorers: [
      {
        name: "Etherscan",
        url: "https://sepolia.etherscan.io",
        apiUrl: "https://api-sepolia.etherscan.io/api",
      },
    ],
    nativeCurrency: { name: "Sepolia Ether", symbol: "ETH", decimals: 18 },
    color: "from-blue-500 to-indigo-600",
    isTestnet: true,
    faucetUrl: "https://sepoliafaucet.com",
    avgBlockTime: 12,
    confirmations: 2,
  },
  {
    id: "poly-amoy",
    chainId: 80002,
    hexChainId: "0x13882",
    name: "Polygon Amoy",
    shortName: "Amoy",
    network: "testnet",
    rpcUrls: [
      "https://rpc-amoy.polygon.technology",
      "https://polygon-amoy.drpc.org",
    ],
    blockExplorers: [
      {
        name: "OKLink",
        url: "https://www.oklink.com/amoy",
      },
    ],
    nativeCurrency: { name: "MATIC", symbol: "MATIC", decimals: 18 },
    color: "from-purple-500 to-pink-600",
    isTestnet: true,
    faucetUrl: "https://faucet.polygon.technology",
    avgBlockTime: 2,
    confirmations: 5,
  },
  {
    id: "base-sepolia",
    chainId: 84532,
    hexChainId: "0x14a34",
    name: "Base Sepolia",
    shortName: "Base Sepolia",
    network: "testnet",
    rpcUrls: [
      "https://sepolia.base.org",
      "https://base-sepolia.blockpi.network/v1/rpc/public",
    ],
    blockExplorers: [
      {
        name: "BaseScan",
        url: "https://sepolia.basescan.org",
        apiUrl: "https://api-sepolia.basescan.org/api",
      },
    ],
    nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
    color: "from-blue-400 to-cyan-500",
    isTestnet: true,
    faucetUrl: "https://www.coinbase.com/faucets/base-ethereum-goerli-faucet",
    avgBlockTime: 2,
    confirmations: 3,
  },
  {
    id: "arb-sepolia",
    chainId: 421614,
    hexChainId: "0x66eee",
    name: "Arbitrum Sepolia",
    shortName: "Arb Sepolia",
    network: "testnet",
    rpcUrls: [
      "https://sepolia-rollup.arbitrum.io/rpc",
      "https://arbitrum-sepolia.blockpi.network/v1/rpc/public",
    ],
    blockExplorers: [
      {
        name: "Arbiscan",
        url: "https://sepolia.arbiscan.io",
        apiUrl: "https://api-sepolia.arbiscan.io/api",
      },
    ],
    nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
    color: "from-blue-600 to-sky-400",
    isTestnet: true,
    faucetUrl: "https://faucet.quicknode.com/arbitrum/sepolia",
    avgBlockTime: 0.25,
    confirmations: 10,
  },
  {
    id: "op-sepolia",
    chainId: 11155420,
    hexChainId: "0xaa37dc",
    name: "Optimism Sepolia",
    shortName: "OP Sepolia",
    network: "testnet",
    rpcUrls: [
      "https://sepolia.optimism.io",
      "https://optimism-sepolia.blockpi.network/v1/rpc/public",
    ],
    blockExplorers: [
      {
        name: "Optimistic Etherscan",
        url: "https://sepolia-optimism.etherscan.io",
      },
    ],
    nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
    color: "from-red-500 to-rose-600",
    isTestnet: true,
    avgBlockTime: 2,
    confirmations: 5,
  },
  {
    id: "avax-fuji",
    chainId: 43113,
    hexChainId: "0xa869",
    name: "Avalanche Fuji",
    shortName: "Fuji",
    network: "testnet",
    rpcUrls: [
      "https://api.avax-test.network/ext/bc/C/rpc",
      "https://avalanche-fuji-c-chain.publicnode.com",
    ],
    blockExplorers: [
      {
        name: "SnowTrace",
        url: "https://testnet.snowtrace.io",
      },
    ],
    nativeCurrency: { name: "Avalanche", symbol: "AVAX", decimals: 18 },
    color: "from-red-600 to-red-400",
    isTestnet: true,
    faucetUrl: "https://faucet.avax.network",
    avgBlockTime: 2,
    confirmations: 3,
  },
  {
    id: "bnb-testnet",
    chainId: 97,
    hexChainId: "0x61",
    name: "BNB Chain Testnet",
    shortName: "BSC Testnet",
    network: "testnet",
    rpcUrls: [
      "https://data-seed-prebsc-1-s1.binance.org:8545",
      "https://bsc-testnet.publicnode.com",
    ],
    blockExplorers: [
      {
        name: "BscScan",
        url: "https://testnet.bscscan.com",
        apiUrl: "https://api-testnet.bscscan.com/api",
      },
    ],
    nativeCurrency: { name: "BNB", symbol: "BNB", decimals: 18 },
    color: "from-yellow-500 to-amber-600",
    isTestnet: true,
    faucetUrl: "https://testnet.bnbchain.org/faucet-smart",
    avgBlockTime: 3,
    confirmations: 5,
  },
];
